// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTc-A-aV_nJEYKQb05-pCBYactaSlHBuM',
    appId: '1:411225070178:android:42a86546d4d87592058f3b',
    messagingSenderId: '411225070178',
    projectId: 'trab-brademo-gabi-45984',
    storageBucket: 'trab-brademo-gabi-45984.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYGGnx5GgrXnG0m7-AbE-bxsugliERNNg',
    appId: '1:411225070178:ios:c2c0ee76e0ce97b7058f3b',
    messagingSenderId: '411225070178',
    projectId: 'trab-brademo-gabi-45984',
    storageBucket: 'trab-brademo-gabi-45984.firebasestorage.app',
    iosBundleId: 'com.example.trabalho01',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYGGnx5GgrXnG0m7-AbE-bxsugliERNNg',
    appId: '1:411225070178:ios:c2c0ee76e0ce97b7058f3b',
    messagingSenderId: '411225070178',
    projectId: 'trab-brademo-gabi-45984',
    storageBucket: 'trab-brademo-gabi-45984.firebasestorage.app',
    iosBundleId: 'com.example.trabalho01',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOiKKpAeeHLNFhVOKQw16qr2FYrAC3V7A',
    appId: '1:411225070178:web:fbf2f3716d978d21058f3b',
    messagingSenderId: '411225070178',
    projectId: 'trab-brademo-gabi-45984',
    authDomain: 'trab-brademo-gabi-45984.firebaseapp.com',
    storageBucket: 'trab-brademo-gabi-45984.firebasestorage.app',
    measurementId: 'G-76X24TBZRF',
  );

}